import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// `eslint-config-next` still ships in the legacy (.eslintrc) format, so we wrap
// it with FlatCompat to use it from a flat config file. Drop the wrapper when
// Next publishes a native flat config export.
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "node_modules/**",
      // Source-of-truth design export from the design tool. Vendor code, not ours.
      "design_handoff_sprint_site/**",
      // Generated by Next on every build.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
