import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// `eslint-config-next` still ships in the legacy (.eslintrc) format, so we wrap
// it with FlatCompat to use it from a flat config file. Drop the wrapper when
// Next publishes a native flat config export.
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    // Patterns are anchored to this directory unless they start with `**/`.
    // Use `**/` for anything that can also appear in a nested copy of the repo.
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "out/**",
      "build/**",
      // Claude Code creates git worktrees here. Each one is a full copy of the
      // repo, so without this ESLint reports every problem twice. Flat config
      // does not skip dot-directories on its own.
      ".claude/**",
      // Source-of-truth design export from the design tool. Vendor code, not ours.
      "**/design_handoff_sprint_site/**",
      // Generated by Next on every build.
      "**/next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
